# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_cadastrar = QtWidgets.QLabel(self.centralwidget)
        self.label_cadastrar.setGeometry(QtCore.QRect(270, 20, 91, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(19)
        sizePolicy.setHeightForWidth(self.label_cadastrar.sizePolicy().hasHeightForWidth())
        self.label_cadastrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_cadastrar.setFont(font)
        self.label_cadastrar.setObjectName("label_cadastrar")
        self.botao_cadastrar_cliente = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastrar_cliente.setGeometry(QtCore.QRect(220, 110, 191, 23))
        self.botao_cadastrar_cliente.setObjectName("botao_cadastrar_cliente")
        self.botao_criar_conta = QtWidgets.QPushButton(self.centralwidget)
        self.botao_criar_conta.setGeometry(QtCore.QRect(220, 160, 191, 23))
        self.botao_criar_conta.setObjectName("botao_criar_conta")
        self.botao_login = QtWidgets.QPushButton(self.centralwidget)
        self.botao_login.setGeometry(QtCore.QRect(220, 210, 191, 23))
        self.botao_login.setObjectName("botao_login")
        self.edit_numero_conta = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_numero_conta.setEnabled(False)
        self.edit_numero_conta.setGeometry(QtCore.QRect(350, 350, 41, 20))
        self.edit_numero_conta.setReadOnly(False)
        self.edit_numero_conta.setPlaceholderText("")
        self.edit_numero_conta.setClearButtonEnabled(False)
        self.edit_numero_conta.setObjectName("edit_numero_conta")
        self.label_numero_contas = QtWidgets.QLabel(self.centralwidget)
        self.label_numero_contas.setGeometry(QtCore.QRect(230, 350, 121, 20))
        self.label_numero_contas.setObjectName("label_numero_contas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_cadastrar.setText(_translate("MainWindow", "Menu"))
        self.botao_cadastrar_cliente.setText(_translate("MainWindow", "Cadastrar Cliente"))
        self.botao_criar_conta.setText(_translate("MainWindow", "Criar Conta"))
        self.botao_login.setText(_translate("MainWindow", "Login"))
        self.label_numero_contas.setText(_translate("MainWindow", "Numero de contas:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
