# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 478)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastrar.setGeometry(QtCore.QRect(280, 220, 75, 23))
        self.botao_cadastrar.setObjectName("botao_cadastrar")
        self.edit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_nome.setGeometry(QtCore.QRect(220, 100, 181, 20))
        self.edit_nome.setReadOnly(False)
        self.edit_nome.setClearButtonEnabled(True)
        self.edit_nome.setObjectName("edit_nome")
        self.label_cadastrar = QtWidgets.QLabel(self.centralwidget)
        self.label_cadastrar.setGeometry(QtCore.QRect(210, 10, 221, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(19)
        sizePolicy.setHeightForWidth(self.label_cadastrar.sizePolicy().hasHeightForWidth())
        self.label_cadastrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_cadastrar.setFont(font)
        self.label_cadastrar.setObjectName("label_cadastrar")
        self.edit_sobrenome = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_sobrenome.setGeometry(QtCore.QRect(220, 140, 181, 20))
        self.edit_sobrenome.setClearButtonEnabled(True)
        self.edit_sobrenome.setObjectName("edit_sobrenome")
        self.edit_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_cpf.setGeometry(QtCore.QRect(220, 180, 181, 20))
        self.edit_cpf.setClearButtonEnabled(True)
        self.edit_cpf.setObjectName("edit_cpf")
        self.botao_menu = QtWidgets.QPushButton(self.centralwidget)
        self.botao_menu.setGeometry(QtCore.QRect(510, 390, 86, 26))
        self.botao_menu.setObjectName("botao_menu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botao_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.edit_nome.setPlaceholderText(_translate("MainWindow", "NOME"))
        self.label_cadastrar.setText(_translate("MainWindow", "Cadastrar cliente"))
        self.edit_sobrenome.setPlaceholderText(_translate("MainWindow", "SOBRENOME"))
        self.edit_cpf.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.botao_menu.setText(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
