# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCriarConta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaCriarConta(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_cadastrar = QtWidgets.QLabel(self.centralwidget)
        self.label_cadastrar.setGeometry(QtCore.QRect(250, 40, 141, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(19)
        sizePolicy.setHeightForWidth(self.label_cadastrar.sizePolicy().hasHeightForWidth())
        self.label_cadastrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_cadastrar.setFont(font)
        self.label_cadastrar.setObjectName("label_cadastrar")
        self.edit_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_cpf.setGeometry(QtCore.QRect(220, 130, 181, 20))
        self.edit_cpf.setText("")
        self.edit_cpf.setReadOnly(False)
        self.edit_cpf.setClearButtonEnabled(True)
        self.edit_cpf.setObjectName("edit_cpf")
        self.botao_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastrar.setGeometry(QtCore.QRect(420, 130, 75, 23))
        self.botao_cadastrar.setObjectName("botao_cadastrar")
        self.botao_menu = QtWidgets.QPushButton(self.centralwidget)
        self.botao_menu.setGeometry(QtCore.QRect(510, 410, 86, 26))
        self.botao_menu.setObjectName("botao_menu")
        self.edit_numero_conta = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_numero_conta.setEnabled(False)
        self.edit_numero_conta.setGeometry(QtCore.QRect(230, 230, 181, 20))
        self.edit_numero_conta.setText("")
        self.edit_numero_conta.setReadOnly(False)
        self.edit_numero_conta.setPlaceholderText("")
        self.edit_numero_conta.setClearButtonEnabled(True)
        self.edit_numero_conta.setObjectName("edit_numero_conta")
        self.label_numero_conta = QtWidgets.QLabel(self.centralwidget)
        self.label_numero_conta.setGeometry(QtCore.QRect(110, 230, 111, 20))
        self.label_numero_conta.setObjectName("label_numero_conta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_cadastrar.setText(_translate("MainWindow", "Criar conta"))
        self.edit_cpf.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.botao_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.botao_menu.setText(_translate("MainWindow", "Menu"))
        self.label_numero_conta.setText(_translate("MainWindow", "Numero da conta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaCriarConta()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
