from PyQt5 import QtCore, QtGui, QtWidgets


class TelaBusca(object):
    def setupUi(self, Besteira):
        Besteira.setObjectName("Besteira")
        Besteira.resize(641, 436)
        self.centralwidget = QtWidgets.QWidget(Besteira)
        self.centralwidget.setObjectName("centralwidget")
        self.button_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.button_buscar.setGeometry(QtCore.QRect(90, 100, 75, 23))
        icon = QtGui.QIcon.fromTheme("aa")
        self.button_buscar.setIcon(icon)
        self.button_buscar.setObjectName("button_buscar")
        self.edit_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_cpf.setGeometry(QtCore.QRect(170, 100, 171, 21))
        self.edit_cpf.setAccessibleDescription("")
        self.edit_cpf.setInputMask("")
        self.edit_cpf.setText("")
        self.edit_cpf.setClearButtonEnabled(True)
        self.edit_cpf.setObjectName("edit_cpf")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setEnabled(False)
        self.name.setGeometry(QtCore.QRect(90, 210, 241, 20))
        self.name.setObjectName("name")
        self.endereco = QtWidgets.QLineEdit(self.centralwidget)
        self.endereco.setEnabled(False)
        self.endereco.setGeometry(QtCore.QRect(90, 270, 241, 20))
        self.endereco.setObjectName("endereco")
        self.nascimento = QtWidgets.QLineEdit(self.centralwidget)
        self.nascimento.setEnabled(False)
        self.nascimento.setGeometry(QtCore.QRect(90, 320, 241, 20))
        self.nascimento.setObjectName("nascimento")
        self.label_nascimento = QtWidgets.QLabel(self.centralwidget)
        self.label_nascimento.setGeometry(QtCore.QRect(340, 320, 81, 16))
        self.label_nascimento.setObjectName("label_nascimento")
        self.label_endereco = QtWidgets.QLabel(self.centralwidget)
        self.label_endereco.setGeometry(QtCore.QRect(340, 270, 81, 16))
        self.label_endereco.setObjectName("label_endereco")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(340, 210, 81, 16))
        self.label_nome.setObjectName("label_nome")
        self.button_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.button_voltar.setGeometry(QtCore.QRect(520, 370, 75, 23))
        icon = QtGui.QIcon.fromTheme("aa")
        self.button_voltar.setIcon(icon)
        self.button_voltar.setObjectName("button_voltar")
        Besteira.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Besteira)
        self.statusbar.setObjectName("statusbar")
        Besteira.setStatusBar(self.statusbar)

        self.retranslateUi(Besteira)
        QtCore.QMetaObject.connectSlotsByName(Besteira)

    def retranslateUi(self, Besteira):
        _translate = QtCore.QCoreApplication.translate
        Besteira.setWindowTitle(_translate("Besteira", "MainWindow"))
        self.button_buscar.setText(_translate("Besteira", "Buscar"))
        self.edit_cpf.setPlaceholderText(_translate("Besteira", "CPF"))
        self.label_nascimento.setText(_translate("Besteira", "Nascimento"))
        self.label_endereco.setText(_translate("Besteira", "endereço"))
        self.label_nome.setText(_translate("Besteira", "Nome"))
        self.button_voltar.setText(_translate("Besteira", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela = QtWidgets.QMainWindow()
    ui = TelaBusca()
    ui.setupUi(tela)
    tela.show()
    sys.exit(app.exec_())
