import psycopg2

connection = psycopg2.connect(user = 'postgres', password= '1234', host= 'localhost', port= '5432', database= 'bd')
cursor = connection.cursor()

sql = """CREATE TABLE IF NOT EXISTS usuarios(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome text NOT NULL, email text NOT NULL);"""

nome = "weliton"
email = "weliton@gmail.com"

cursor.execute(sql)

for index in range(2):
    cursor.execute('INSERT INTO usuarios (nome, email) VALUES (%s, %s)', (nome, email))

cursor.execute('SELECT * FROM usuarios')
for usuario in cursor:
    print(list(usuario))

connection.commit()
connection.close()

