import psycopg2

connection = psycopg2.connect(user = 'postgres', password= '1234', host= 'localhost', port= '5432', database= 'bd')
cursor = connection.cursor()

sql = """CREATE TABLE IF NOT EXISTS usuarios_senha(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome text NOT NULL, email text NOT NULL, senha text NOT NULL);"""

nome = "weliton"
email = "weliton@gmail.com"
senha = "1234"

cursor.execute(sql)

for index in range(2):
    cursor.execute('INSERT INTO usuarios_senha (nome, email, senha) VALUES (%s, %s, MD5(%s))', (nome, email, senha))

cursor.execute('SELECT * FROM usuarios_senha')
for usuario in cursor:
    print(list(usuario))

connection.commit()
connection.close()