# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_extrato.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaExtrato(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_conta_aberta = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_conta_aberta.setEnabled(False)
        self.edit_conta_aberta.setGeometry(QtCore.QRect(290, 160, 181, 20))
        self.edit_conta_aberta.setReadOnly(False)
        self.edit_conta_aberta.setObjectName("edit_conta_aberta")
        self.label_conta_aberta = QtWidgets.QLabel(self.centralwidget)
        self.label_conta_aberta.setGeometry(QtCore.QRect(180, 160, 111, 20))
        self.label_conta_aberta.setObjectName("label_conta_aberta")
        self.label_saldo = QtWidgets.QLabel(self.centralwidget)
        self.label_saldo.setGeometry(QtCore.QRect(240, 200, 41, 16))
        self.label_saldo.setObjectName("label_saldo")
        self.edit_saldo = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_saldo.setEnabled(False)
        self.edit_saldo.setGeometry(QtCore.QRect(290, 200, 181, 20))
        self.edit_saldo.setReadOnly(True)
        self.edit_saldo.setObjectName("edit_saldo")
        self.botao_menu = QtWidgets.QPushButton(self.centralwidget)
        self.botao_menu.setGeometry(QtCore.QRect(290, 260, 86, 26))
        self.botao_menu.setObjectName("botao_menu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_conta_aberta.setText(_translate("MainWindow", "Conta aberta em"))
        self.label_saldo.setText(_translate("MainWindow", "Saldo"))
        self.botao_menu.setText(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaExtrato()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
