# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaLogin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_numero_conta = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_numero_conta.setGeometry(QtCore.QRect(220, 110, 181, 20))
        self.edit_numero_conta.setReadOnly(False)
        self.edit_numero_conta.setClearButtonEnabled(True)
        self.edit_numero_conta.setObjectName("edit_numero_conta")
        self.botao_menu = QtWidgets.QPushButton(self.centralwidget)
        self.botao_menu.setGeometry(QtCore.QRect(520, 390, 86, 26))
        self.botao_menu.setObjectName("botao_menu")
        self.botao_transferir = QtWidgets.QPushButton(self.centralwidget)
        self.botao_transferir.setGeometry(QtCore.QRect(270, 240, 75, 23))
        self.botao_transferir.setObjectName("botao_transferir")
        self.botao_historico = QtWidgets.QPushButton(self.centralwidget)
        self.botao_historico.setGeometry(QtCore.QRect(270, 280, 75, 23))
        self.botao_historico.setObjectName("botao_historico")
        self.botao_depositar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_depositar.setGeometry(QtCore.QRect(270, 160, 75, 23))
        self.botao_depositar.setObjectName("botao_depositar")
        self.botao_sacar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_sacar.setGeometry(QtCore.QRect(270, 200, 75, 23))
        self.botao_sacar.setObjectName("botao_sacar")
        self.botao_extrato = QtWidgets.QPushButton(self.centralwidget)
        self.botao_extrato.setGeometry(QtCore.QRect(270, 320, 75, 23))
        self.botao_extrato.setObjectName("botao_extrato")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.edit_numero_conta.setPlaceholderText(_translate("MainWindow", "NUMERO DA CONTA"))
        self.botao_menu.setText(_translate("MainWindow", "Menu"))
        self.botao_transferir.setText(_translate("MainWindow", "Transferir"))
        self.botao_historico.setText(_translate("MainWindow", "Historico"))
        self.botao_depositar.setText(_translate("MainWindow", "Depositar"))
        self.botao_sacar.setText(_translate("MainWindow", "Sacar"))
        self.botao_extrato.setText(_translate("MainWindow", "Extrato"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaLogin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
